apt update
apt install apt
apt install bash
apt install busybox
apt install clang
apt install dpkg
apt install elinks
apt install emacs
apt install fsmon
apt install gdb
apt install gnupg
apt install htop
apt install imagemagick
apt install libandroid-support
apt install libgnustl
apt install liblzma
apt install macchanger
apt install make
apt install man
apt install mc
apt install ncurses
apt install nmap
apt install openssh
apt install python
apt install readline
apt install ruby
apt install tar
apt install tmux
apt install vim
apt install zsh
